version: '3.7'

services:
  # colyseus:
  #   build:
  #     context: ./new-server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "2567:2567"
  #   volumes:
  #     - ./new-server:/app  # bind-mount source code
  #     - node_modules:/app/node_modules  # named volume for node_modules

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - colyseus

volumes:
  node_modules:
