version: '3'
services:
  server:
    build: 
      context: ./server
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  client:
    build: 
      context: ./client
    volumes:
      - ./client:/app
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_GAME_SERVER=http://server:3000
    depends_on:
      - server